LeftAndMain:
  extra_requirements_javascript:
    - 'shortcodable/javascript/editor_plugin.js'
    - 'shortcodable/javascript/shortcodable.js'
  extra_requirements_css:
    - 'shortcodable/css/shortcodable.css'

Director:
  rules:
    'admin/shortcodable': ShortcodableController

Shortcodable:
  htmleditor_names:
    - cms

HtmlEditorField:
  extensions:
    - ShortcodableHtmlEditorField

ShortcodeParser:
  extensions:
    - ShortcodableShortcodeParserExtension
